// Generated by msggen from MsggenMessages.xml
package org.kopi.compiler.tools.msggen;

import org.kopi.util.base.MessageDescription;

public interface MsggenMessages extends org.kopi.compiler.base.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Message \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
}
