@package com.kopiright.xkopi.comp.dbi
@vocabulary	Dbi

@literal	ACCESS
@literal	ADD
@literal	ALTER
@literal	BYTE
@literal	CASCADE
@literal	CODE
@literal	COLOR
@literal	COLUMN
@literal	CONSTRAINT
@literal	CONVERT
@literal	CREATE
@literal	DATE
@literal	DATETIME
@literal	DBA
@literal	DELIM
@literal	DISALLOW
@literal	DROP
@literal	ENUM
@literal	FIXED
@literal	FOREIGN
// UNUSED @literal	FRACTION
@literal	GRANT
@literal	IGNORE
@literal	IMAGE
@literal	INDEX
@literal	INT
@literal	KEY
@literal	LOCAL
@literal	LONG
@literal	LOWER
@literal	MAXVAL
@literal	MINVAL
@literal	MONTH
@literal	NAME
@literal	OPTION
@literal	PRAGMA
@literal	PRIMARY
@literal	PUBLIC
@literal	REFERENCES
@literal	RESTRICT
@literal	RESOURCE
@literal        SEQUENCE
@literal	SHORT
@literal	SORTED
@literal	SPOOL
@literal        START
@literal	TAB
@literal	TEXT
@literal	TIME
@literal	TIMESTAMP
@literal	TO
@literal	UNIQUE
@literal	UPPER
@literal	VIEW
@literal	VERSION
@literal	WEEK
@literal	WITH
