@package com.kopiright.vkopi.comp.form
@vocabulary Form

@literal	ALIGN
@literal	AUTOLEAVE
@literal	AT
@literal	BEGIN
@literal	BORDER
@literal	CENTER
@literal	CHANGED
@literal	CHART
@literal	COLUMNS
@literal	DEFAULT
@literal	DELETE
@literal	DETAIL
@literal	ETCHED
@literal	FIELD
@literal	FOLLOW
@literal	FORM
@literal	FORMAT
@literal	HIDDEN
@literal	IMPLEMENTS
@literal	INDEX
@literal	INIT
@literal	LEFT
@literal	LINE
@literal	LOWERED
@literal	MOVE
@literal	MUSTFILL
@literal	NO
@literal	NOECHO
@literal	NOEDIT
@literal	PAGE
@literal	POSTBLK
@literal	POSTCHG
@literal	POSTDEL
@literal	POSTFLD
@literal	POSTFORM
@literal	POSTINS
@literal	POSTQRY
@literal	POSTREC
@literal	POSTUPD
@literal	PREBLK
@literal	PREDEL
@literal	PREFLD
@literal	PREFORM
@literal	PREINS
@literal	PREQRY
@literal	PREREC
@literal	PRESAVE
@literal	PREUPD
@literal	PREVAL
@literal	PRIORITY
@literal	QUERY
@literal	QUITFORM
@literal	RAISED
@literal	RESET
@literal	RIGHT
@literal	SKIPPED
@literal	SLAVES
@literal	SORTABLE
@literal	TABLE
@literal	TRANSIENT
@literal	UPDATE
@literal	VALBLK
@literal	VALFLD
@literal	VALIDATE
@literal	VALREC
@literal	VALUE
@literal	VISIT
@literal	NULLABLE
@literal	DROPPABLE

@operator	GT	">"
@operator	LT	"<"

