
/*
 * Copyright (c) 1990-2009 kopiRight Managed Solutions GmbH
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * $Id$
 */

// Generated by msggen from OptgenMessages.msg
package com.kopiright.compiler.tools.optgen;

import com.kopiright.util.base.MessageDescription;

public interface OptgenMessages extends com.kopiright.compiler.base.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Option \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
  MessageDescription	DUPLICATE_SHORTCUT = new MessageDescription("Shortcut \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
}
