// Generated by msggen from OptgenMessages.xml
package com.kopiright.compiler.tools.optgen;

import com.kopiright.util.base.MessageDescription;

public interface OptgenMessages extends com.kopiright.compiler.base.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Option \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
  MessageDescription	DUPLICATE_SHORTCUT = new MessageDescription("Shortcut \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
}
