##
## Copyright (c) 1990-2007 kopiRight Managed Solutions GmbH
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 2
## as published by the Free Software Foundation.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.2 2002/05/27 15:39:15 laurent Exp $

TOPDIR =	../../..

PACKAGE =	com/kopiright/xkopi/comp/database


## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES  +=	DatabaseMember DatabaseTable           \
                DatabaseColumn DatabaseClobColumn DatabaseIntegerColumn \
                DatabaseStringColumn DatabaseTimestampColumn            \
                DatabaseEnumColumn  DatabaseImageColumn                 \
                DatabaseDateColumn  DatabaseMonthColumn                 \
                DatabaseFixedColumn  DatabaseTextColumn                 \
                DatabaseWeekColumn  DatabaseBooleanColumn               \
                DatabaseColorColumn DatabaseTimeColumn                  \
                DatabaseShortColumn DatabaseByteColumn                  \
                DatabaseBlobColumn DatabaseCardinalColumn

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
