##
## Copyright (C) 1990-2001 DMS Decision Management Systems Ges.m.b.H.
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License as published by the Free Software Foundation; either
## version 2 of the License, or (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.6 2003/05/12 15:19:42 lackner Exp $
##

TOPDIR =	../../../..

PACKAGE =	at/dms/vkopi/lib/ui/plaf

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	KopiLabelUI KopiFieldLabelUI KopiLookAndFeel KopiTheme	\
		KopiTextFieldUI KopiTabbedPaneUI KopiScrollBarUI	\
		KopiButtonUI KopiTextAreaUI KopiUtils			\
		KopiPasswordFieldUI KopiProgressBarUI			\
		KopiUserColors KopiToggleButtonUI

OPTIONS =

PROPERTIES =

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
