/*
 * Copyright (c) 1990-2009 kopiRight Managed Solutions GmbH
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * $Id$
 */

package com.kopiright.xkopi.comp.sqlc;

public interface Constants {
  public static final String KOPI_SEQUENCES_TABLE = "ALL_KOPI_SEQUENCES";
  public static final String DICT_SEPARATOR = "__";
  public static final String ROWID = "rowid";
  public static final String ROWNUM = "rownum";

  // this list contains reserved database keywords for maxdb
  // and must be extended for other databases
  // these keywords must not be used as table columns or aliases
  // NB : pseudo colums like : rowid or rownum, must be called using {fn ROWID }
  // or {fn ROWNUM} , to make sure to not write a database specific sql code.
  public static final String[] RESERVED_DATABASE_KEYWORDS = new String[] {"ABS",
                                                                          "ABSOLUTE",
                                                                          "ACOS",
                                                                          "ADDDATE",
                                                                          "ADDTIME",
                                                                          "ALL",
                                                                          "ALPHA",
                                                                          "ALTER",
                                                                          "ANY",
                                                                          "ASCII",
                                                                          "ASIN",
                                                                          "ATAN",
                                                                          "ATAN2",
                                                                          "AVG",
                                                                          "BINARY",
                                                                          "BIT",
                                                                          "BOOLEAN",
                                                                          "BYTE",
                                                                          "CASE",
                                                                          "CEIL",
                                                                          "CEILING",
                                                                          "CHAR",
                                                                          "CHARACTER",
                                                                          "CHECK",
                                                                          "CHR",
                                                                          "COLUMN",
                                                                          "CONCAT",
                                                                          "CONSTRAINT",
                                                                          "COS",
                                                                          "COSH",
                                                                          "COT",
                                                                          "COUNT",
                                                                          "CROSS",
                                                                          "CURDATE",
                                                                          "CURRENT",
                                                                          "CURTIME",
                                                                          "DATABASE",
                                                                          "DATE",
                                                                          "DATEDIFF",
                                                                          "DAY",
                                                                          "DAYNAME",
                                                                          "DAYOFMONTH",
                                                                          "DAYOFWEEK",
                                                                          "DAYOFYEAR",
                                                                          "DBYTE",
                                                                          "DEC",
                                                                          "DECIMAL",
                                                                          "DECODE",
                                                                          "DEFAULT",
                                                                          "DEGREES",
                                                                          "DELETE",
                                                                          "DIGITS",
                                                                          "DISTINCT",
                                                                          "DOUBLE",
                                                                          "EBCDIC",
                                                                          "EXCEPT",
                                                                          "EXISTS",
                                                                          "EXP",
                                                                          "EXPAND",
                                                                          "FIRST",
                                                                          "FIXED",
                                                                          "FLOAT",
                                                                          "FLOOR",
                                                                          "FOR",
                                                                          "FROM",
                                                                          "FULL",
                                                                          "GET_OBJECTNAME",
                                                                          "GET_OWNER",
                                                                          "GRAPHIC",
                                                                          "GREATEST",
                                                                          "GROUP",
                                                                          "HAVING",
                                                                          "HEX",
                                                                          "HEXTORAW",
                                                                          "HOUR",
                                                                          "IFNULL",
                                                                          "IGNORE",
                                                                          "INDEX",
                                                                          "INITCAP",
                                                                          "INNER",
                                                                          "INSERT",
                                                                          "INT",
                                                                          "INTEGER",
                                                                          "INTERNAL",
                                                                          "INTERSECT",
                                                                          "INTO",
                                                                          "JOIN",
                                                                          "KEY",
                                                                          "LAST",
                                                                          "LCASE",
                                                                          "LEAST",
                                                                          "LEFT",
                                                                          "LENGTH",
                                                                          "LFILL",
                                                                          "LINK",
                                                                          "LIST",
                                                                          "LN",
                                                                          "LOCATE",
                                                                          "LOG",
                                                                          "LOG10",
                                                                          "LONG",
                                                                          "LONGFILE",
                                                                          "LOWER",
                                                                          "LPAD",
                                                                          "LTRIM",
                                                                          "MAKEDATE",
                                                                          "MAKETIME",
                                                                          "MAPCHAR",
                                                                          "MAX",
                                                                          "MBCS",
                                                                          "MICROSECOND",
                                                                          "MIN",
                                                                          "MINUTE",
                                                                          "MOD",
                                                                          "MONTH",
                                                                          "MONTHNAME",
                                                                          "NATURAL",
                                                                          "NCHAR",
                                                                          "NEXT",
                                                                          "NO",
                                                                          "NOROUND",
                                                                          "NOT",
                                                                          "NOW",
                                                                          "NULL",
                                                                          "NUM",
                                                                          "NUMERIC",
                                                                          "OBJECT",
                                                                          "OF",
                                                                          "ON",
                                                                          "ORDER",
                                                                          "PACKED",
                                                                          "PI",
                                                                          "POWER",
                                                                          "PREV",
                                                                          "PRIMARY",
                                                                          "RADIANS",
                                                                          "REAL",
                                                                          "REJECT",
                                                                          "RELATIVE",
                                                                          "REPLACE",
                                                                          "RFILL",
                                                                          "RIGHT",
                                                                          "ROUND",
                                                                          "ROWID",
                                                                          "ROWNO",
                                                                          "RPAD",
                                                                          "RTRIM",
                                                                          "SECOND",
                                                                          "SELECT",
                                                                          "SELUPD",
                                                                          "SERIAL",
                                                                          "SET",
                                                                          "SHOW",
                                                                          "SIGN",
                                                                          "SIN",
                                                                          "SINH",
                                                                          "SMALLINT",
                                                                          "SOME",
                                                                          "SOUNDEX",
                                                                          "SPACE",
                                                                          "SQRT",
                                                                          "STAMP",
                                                                          "STATISTICS",
                                                                          "STDDEV",
                                                                          "SUBDATE",
                                                                          "SUBSTR",
                                                                          "SUBSTRING",
                                                                          "SUBTIME",
                                                                          "SUM",
                                                                          "SYSDBA",
                                                                          "TABLE",
                                                                          "TAN",
                                                                          "TANH",
                                                                          "TIME",
                                                                          "TIMEDIFF",
                                                                          "TIMESTAMP",
                                                                          "TIMEZONE",
                                                                          "TO",
                                                                          "TOIDENTIFIER",
                                                                          "TRANSACTION",
                                                                          "TRANSLATE",
                                                                          "TRIM",
                                                                          "TRUNC",
                                                                          "TRUNCATE",
                                                                          "UCASE",
                                                                          "UID",
                                                                          "UNICODE",
                                                                          "UNION",
                                                                          "UPDATE",
                                                                          "UPPER",
                                                                          "USER",
                                                                          "USERGROUP",
                                                                          "USING",
                                                                          "UTCDATE",
                                                                          "UTCDIFF",
                                                                          "VALUE",
                                                                          "VALUES",
                                                                          "VARCHAR",
                                                                          "VARGRAPHIC",
                                                                          "VARIANCE",
                                                                          "WEEK",
                                                                          "WEEKOFYEAR",
                                                                          "WHEN",
                                                                          "WHERE",
                                                                          "WITH",
                                                                          "YEAR",
                                                                          "ZONED"};
}
