// Generated by msggen from AntlrMessages.msg
package com.kopiright.compiler.tools.antlr.compiler;

import com.kopiright.util.base.MessageDescription;

public interface AntlrMessages extends com.kopiright.compiler.base.CompilerMessages {
}
