
=== Visual Kopi Charts

Visual Kopi allows you to create charts. These are files with the ".vc" extension that have a very simple structure, in fact, all you have to do to create such charts
is to define the dimensions you need and their measures, then you will have to write a constructor that will load data into these fields.
With kopi Charts, you will also be able to print or export the created chart to different file formats.

The Visual Kopi Charts are generated from Visual Kopi form files with the ".vc" extension by different methods that we will see in this chapter, along with the process of making a
visual charts.

==== Creating Charts dimensions and measures

As we said in the introduction, the chart structure is based on chart dimensions and measures.
The dimension field begins with DIMENSION and a SimpleName and ends with END DIMENSION and have the following syntax :

*Syntax*
[source,java]
----
ChartDimensionDef: "DIMENSION" [Integer MultiDimension] SimpleName [DimensionLabel]
                [HelpText] DimensionType [DimensionCommands] [DimensionTriggers]
                "END" "DIMENSION"
----

The measure field begins with MEASURE and a SimpleName and ends with END MEASURE and have the following syntax :

*Syntax*
[source,java]
----
ChartDimensionDef: "MEASURE" [Integer MultiMeasure] SimpleName [MeasureLabel]
                [HelpText] MeasureType [MeasureCommands] [MeasureTriggers]
                "END" "MEASURE"
----

===== Single "dimension / measure" and Multiple "dimensions / measures"

When you define a news chart dimension or measure, you have the choice to make it multiple by adding an integer (i) just after the DIMENSION / MEASURE command, doing so will create i fields.
The generated fields will have the SimpleName indicated after the DIMENSION / MEASURE command plus a number from 1 to i.

*Example*
[source,java]
----
MEASURE(3) Name
  ...
END MEASURE
----
In this example we have created 3 measures (Name1, Name2 and Name3).

=====  Chart "dimension / measure" Label

The label is the name that will be shown in the chart, you can define a label by entering the LABEL command followed by String separated with a comma. If you omit the Strings after the LABEL command, the "dimension / measure" 
will have its SimpleName as label. You can also specify NO LABEL if you want your field to have no label at all.
If you specify more than one String after the LABEL command, then if your "dimension / measure" is Single it will have the first String as label, otherwise, if it's a multiple "dimension / measure" each generated field will have a label 
from the Strings by order.

*Example*
[source,java]
----
DIMENSION Name
  LABEL "Person Name"
  ...
END DIMENSION


DIMENSION(3) LastName
  LABEL "Name1", "Name2", "Name3"
  ...
END DIMENSION


MEASURE Age
  LABEL
  ...
END MEASURE


DIMENSION ID
  NO LABEL
  ...
END DIMENSION
---- 

===== Chart "dimension / measure" Help Text

HELP is used to insert an explanation text for the application user . This Help text will then be displayed when the user places the mouse on the chart measure or dimension.

*Example*
[source,java]
----
DIMENSION Name
  LABEL
  HELP *"The Person's First Name"
  ...
END DIMENSION
----

===== Chart dimension Type

The dimension type is a required entry, you may enter a predefined dimension type :

*Example*
[source,java]
----
DIMENSION Name
  LABEL
  STRING(10)
END DIMENSION

DIMENSION Month
  MONTH
END DIMENSION
----

You can also use self defined field types that you have previously defined in the type definition section of your chart.

*Example*
[source,java]
----
DIMENSION objectList
  LABEL
  TYPE Objects
END DIMENSION
----

In this example, Objects is a type you should have defined previously in type definition section of the chart using standard types, CODE types, ENUM types, LIST and SELECT command ...

===== Chart measure Type

The dimension type is a required entry but it is restricted to number types. This means that for a measure you can use only LONG and FIXNUM as types. The measure type is checked at the compilation step.
If you use not a numeric type for a measure, the following compiler error will be revealed :

Measure "Measure name" is not numeric.

The measure type can be defined with different ways :

*Example*
[source,java]
----
MEASURE Name
  LABEL
  LONG(5)
END DIMENSION

MEASURE Name
  LABEL
  TYPE Price
END DIMENSION
----

In the last example, the price type should be a numeric type otherwise it would not be accepted.

===== Chart "dimension / measure" Command

In chart dimensions or measures, you can call commands with one of the following syntaxes :


[source,java]
----
"COMMAND" QualifiedName  
    
Example
COMMAND ExportPNG 
----

Or: 
   
[source,java]
---- 
"COMMAND" "ITEM" SimpleName "CALL" SimpleName "END" "COMMAND"

Example
COMMAND
  ITEM Export
  CALL function
END COMMAND
----

Or: 
   
[source,java]
----
"COMMAND" "ITEM" SimpleName "EXTERN" QualifiedName "END" "COMMAND"
    
Example    
COMMAND 
  ITEM Export
  EXTERN function
END COMMAND
----

Or:

[source,java]
----
"COMMAND" "ITEM" SimpleName "ACTION"
(com.kopiright.vkopi.lib.chart.VColulmn SimpleName) {Kopi-Java Code} 
"END" "COMMAND"
----

Or:

[source,java]
----
"COMMAND" "ITEM" SimpleName "ACTION" {Kopi-Java Code} 
"END" "COMMAND" 
----

===== Chart "dimension / measure" Triggers

Chart dimensions or measures triggers are special events that you can catch to execute other actions.

*Syntax*
[source,java]
----
Trigger      : EventList TrigerAction

EventList    : Event [,EventList]*

TrigerAction : SimpleName | "EXTERN" QualifiedName | {KOPI_JAVA code} |
               (VDimension | VMeasure SimpleNAme){KOPI_JAVA code} 
----

Here is the two triggers available for chart fields (dimensions & measures) :

 * FORMAT  : Called for formatting a dimension value. The trigger should return a com.kopiright.vkopi.lib.chart.VColumnFormat instance. This trigger is not available for measures.
 * COLOR : Called to specify a measure color. The trigger should return a com.kopiright.vkopi.lib.visual.VColor instance. This trigger is not available for dimensions.

*Example*
[source,java]
----
DIMENSION Month
  LABEL
  MONTH
  FORMAT {
    return new VColumnFormat() {
      
      public void format(Object value) {
      	return ((month)value).format("MM.yyyy");
      }
    }
  }
END DIMENSION
  
MEASURE Quantity
  NO LABEL
  LONG(5)
  COLOR {
    return VColor.RED;
  }
END MEASURE  
----

==== Creating Charts

Visual Kopi charts have a unique structure that begin with CHART and ends with END CHART as described by the following syntax :

*Syntax*
[source,java]
----
ChartDefinition   :[CharttLocalization] "CHART" ChartTitle
                   [IS QualifiedName] 
                   ["IMPLEMENTS"  [,QualifiedName]*]
                   [ContextHeader] [CharttHelp] [ChartDefinitions]
                   "BEGIN" [ChartCommands] [ChartTriggers] (ChartFields)
                   [ContextFooter]
                   "END" "CHART"

ChartTitle        :  String Title

ChartDefinitions  : [MenuDefinition] [ActorDefinition] [TypeDefinition]
                    [CommandDefinition]
                    [InsertDefinition]
----

===== Chart Localization

This is an optional step in which you may define the language of your forms menus and messages, the latter have to be defined in xml files.

*Example:*
[source,java]
----
LOCALE "en_EN"
-----

===== Chart Title

Every Chart have to begin with the keyword CHART that you have to follow with a title.


*Example*
 	
[source,java]
----  
CHART "Sold quantities per month"
  ...
END CHART
----

===== Chart Superclass And Interfaces

 * *Superclass:*

*Syntax:*
 	
[source,java]
----  
SuperClass:   "IS" QualifiedName 
----
Every Chart is a class that may extend another Java class by using the optional keyword IS. Otherwise,  Kopi will automatically take over the java.lang.Object QualifiedName.

*Example:*
 	
[source,java]
----  
CHART  "Earnings" IS com.kopiright.vkopi.lib.chart.VChart
----
In other words, the class declaration you have just made specifies the direct superclass of the current class.

 * *Interfaces:*

You can also specify interfaces which the chart may implement by using the IMPLEMENTS option. 

*Syntax*

[source,java]
----
"IMPLEMENTS" QualifiedName [,QualifiedName]*
----

*Example:*
 	
[source,java]
----  
CHART "Earnings" IS com.kopiright.vkopi.lib.chart.VChart
  IMPLEMENTS IChart
  ...
END CHART
----

===== Chart Header

*Syntax:*
 	
[source,java]
----  
ContextHeader:   { PackageDeclaration  ImportDeclarations  }

PackageDeclaration:   <As defined in JLS 7.4> 
ImportDeclarations:   <As defined in JLS 7.5> 
----
The package definition is contained in the header. It consists in defining where this chart belongs to i.e which application, which firm or which person it is related to.

*Example*
 	
[source,java]
----  
CHART "Sold quantities per year"
  {
  package com.kopiright.apps.sales;
  }
  ...
END CHART
----
In this example, the chart belongs to the kopiRight firm and is a part of the application called "sales". In addition to this Java package declaration, you can make a Java import declaration in order to import some classes from other packages. You can add an unlimited number of imports.

*Example*
 	
[source,java]
----  
CHART "Sold quantities per year"
  {
    package com.kopiright.apps.sales;

    import java.util.Hashtable
    import java.util.Vector
  }
   ...
END CHART
----


===== Chart Help Text

After the chart header, you can enter a help text for the chart using the following syntax:

*Syntax*
[source,java]
----
HELP String helpText
----
Actually every chart has a help menu that tries to describe the structure of the chart by giving information about its commands and fields in a document, the help text will be on the top of this help menu document.

*Example*
[source,java]
----
CHART "Ordered quantities per month"

  {
    package com.kopiright.apps.orders;

    import java.util.Hashtable
    import java.util.Vector
  }
  
HELP "This chart lists the ordered quantities per month"
...

END CHART

----

===== Chart Menus Definition

Defining a menu means adding an entry to the menu bar in the top of the chart, you can add actors to this menu later by specifying the menu name in the actor definition. In the menu definition, the LABEL is optional.

*Syntax:*
 	
[source,java]
----  
MenuDefinition:   "MENU" SimpleName ["LABEL" String label]   "END" "MENU" 
----

*Example*
 	
[source,java]
---- 
CHART "Ordered quantities per month"

  {
    package com.kopiright.apps.orders;
  }
  
  MENU newMenu
    LABEL "newMenu"
  END MENU
...
END CHART
----

===== Chart Actors Definition

An Actor is an item to be linked with a command, if its ICON is specified, it will appear in the icon_toolbar located under the menu bar, otherwise, it will only be accessible from the menu bar.
ICON,LABEL and KEY are optional, the KEY being the keyboard shortcut to assign to the actor.


*Syntax:*
 	
[source,java]
----  
ActorDefinition:  "ACTOR" SimpleName
                  "MENU"  SimpleName  
                  ["LABEL" String label]
                  "HELP"  String helpText
                  ["KEY"   String key]
                  ["ICON"  String icon]
                  "END" "ACTOR"
----

*Example*
 	
[source,java]
---- 
CHART "Ordered quantities per month"

  {
    package com.kopiright.apps.orders;
  }
  
  MENU newMenu
    LABEL "newMenu"
  END MENU
  
  ACTOR printChart
    MENU  newMenu
    LABEL "Print"
    HELP  "Print the chart" 
    ICON  "printerIcon"
  END ACTOR
...
END CHART
----

===== Chart Types Definition

After having defined your menus and actor, you can enter different field types definitions based on the standard field types or code field types, you can also use the LIST and SELECT commands
to customize these new types. 

*Syntax:*
----
TypeDefinition:  "TYPE" SimplName "IS" FieldType  [TypeList] "END" "TYPE"
----

*Example*
 	
[source,java]
----  
CHART "Ordered quantities per month"
  {
    package com.kopiright.apps.orders;
  }
  
  TYPE Name IS
    STRING (20,10,4)
    CONVERT UPPER
  END TYPE

  TYPE Lesson IS
    LONG (11)
    MINVAL 0
    MAXVAL 100
  END TYPE
  
  TYPE Answer IS
    CODE BOOL IS
    	"Yes" = TRUE
    	"No"  = FALSE
    END CODE
  END TYPE
  
  TYPE Months IS
    ENUM("January", "February", "March", "April")
  END TYPE 
...
END TYPE
    
  ...
END CHART
----

===== Chart Commands Definition

In this section you may want to define new commands, to do so, all you need is an already defined Actor from which you will call the command in order to execute an Action on the chart. There are 3 ways to define this Action:
every command have an effective ray of action (VDimension | VMeasure, VChart)

 * Calling a function with the CALL command
 * Calling a function outside of the chart using the EXTERN command
 * Simply writing the body of the action using the  ACTION command, the parameters are optional and can be VColumn or VChart. 
 
*Syntax*
[source,java]
----
cmdDef: "COMMAND" QualifiedName
        "ITEM" SimpleName
        commandBody
        "END" "COMMAND"

cmdBody: "CALL" SimpleName | "EXTERN" QualifiedName 
         |"ACTION"
         [(VDimension SimpleName | VMeasure SimpleName | VChart SimpleName)]
         {KOPI_JAVA statements}
----


*Example*

Calling a local action :

[source,java]
----
COMMAND print
  ITEM  printActor
  CALL  printChart
END COMMAND
----

*Example*
Calling an external action : 

[source,java]
----
COMMAND doAction
  ITEM Save
  EXTERN com.kopiright.vkopi.lib.chart.Actions
END COMMAND
----

*Example*
Writing the action's body :

[source,java]
----
COMMAND PrintChart
  ITEM  PrintChart
  ACTION (VChart chart){
    // KOPI_JAVA code
  }
END COMMAND
----

===== Chart Insert Definition
This command allows you to actually define your types, menus, actors, commands in another file, and then insert it in any chart you want, thus avoiding rewriting recurrent definitions. You still can add definition before or after using the INSERT command.

*Syntax* 
[source,java]
----
Insert Definition : "INSERT" String filePath
----

*Example*
[source,java]
----
CHART "Orders"
 
  {
    package com.kopiright.apps.orders;
  }
   
  INSERT "ChartDefault.vc"
  
  TYPE Lesson IS
    LONG(11)
  END TYPE

...  
END CHART    
----

===== Chart Commands Declaration

After the Definitions section of the chart, you have to enter the BEGIN keyword in order to begin the chart declaration part where you can optionally call chart commands and triggers, and where you have to enter the chart's fields (dimensions and measures).
Concerning the commands declaration, you can start by the CHART COMMAND statement that add all the default chart commands to your chart that include printing and exporting the chart.
Now you may call other commands using the COMMAND keyword followed by a defined command name from those who already exist or the ones you defined in the command definition section.

*Example*
[source,java]
----
COMMAND SwitchAxis
COMMAND PrintChart
----

You can also define your command when declaring it instead of defining it in the command definition section of the chart, simply write the command definition like explained before, but with no name, in the command declaration section of the chart.

*Example*
[source,java]
----
COMMAND
  ITEM actorName
  ACTION {
    KOPI_JAVA code  
  }
END COMMAND


COMMAND 
  ITEM actorName
  CALL localFunction
END COMMAND
----

===== Chart Triggers Declaration

Chart Triggers are special events that once switched on you can execute a set of actions defined by the following syntax :

*Syntax*
----
ChartTrigger  :    ChartEventList TriggerAction
ChartEventList:    ChartEvent*
----

Kopi actually defines 4 chart Triggers or chart Events : 

 * PRECHART  : executed before the chart is displayed.
 * INIT      : executed at chart initialization.
 * CHARTTYPE : executed after the chart initialization. This trigger should return com.kopiright.vkopi.lib.chart.VChartType and will a fixed type for the chart.
 * POSTCHART : executed after the chart is closed.

*Example*
[source, java]
----
CHART "Orders"
{
  package at.dms.app.application
}

INSERT "ChartDefault.vc"

BEGIN

  CHART COMMAND

  PRECHART {
    System.out.println("This message is displayed before the chart appears");
  }
  
  CHARTTYPE {
    return VChartType.PIE;
  }
  ...
END CHART
----

===== Chart Fields Declaration 

As you already know, a chart is based on field that will be shown as chart series, in this section you have to write at least on dimension and one measure definition or more following 
the definition and the structure we saw in the previous chapter.

===== Chart Context Footer:

This section should follow the chart fields (dimensions and measures) declaration and have to be placed between curly braces, here you may define all the functions, data, classes you need in your chart, written in KOPI_JAVA code.
But most important, you need to define the constructor of you chart, this constructor will be responsible of filling the chart's lines or rows.
All you need to do is importing your data (a List or vector parameter, database query cursors ...) , declaring a row in the chart then add the add(); statement to add the row to the chart.
The constructor may have different parameters but a DBContextHandler object is compulsory (a form most of the time)
For example here is the constructor of a chart named UserChart with 1 measure (Month) and one dimension (Quantity). We will retrieve data from the Orders table on the database. 

*Example*
[source,java]
----
void UserChart(DBContextHandler ctxt) throws VException {
  super(ctxt);
  #protected () {
    try {
      #cursor (){
        SELECT month O.Month,
               int O.Quantity
    
        FROM    Orders O
  
      } cursor;
    
      cursor.open();
    
      while (cursor.next()) 
      {
        Month = cursor.O.Month;
        Quantity  = cursor.O.Quantity;
        add();
      }
      cursor.close();
   } catch (DBNoRowException) {
        System.out.println("DBNoRowException");
      }
  }
}

----

==== Chart types

Kopi offers five predefined chart types :

  * Pie charts
  * Bar charts
  * Column charts
  * Line charts
  * Area charts
  
The chart type can be defined by calling the setType(VChartType) method. The VChartType class contains the five definitions described above :

  * VChartType.PIE
  * VChartType.BAR
  * VChartType.COLUMN
  * VChartType.LINE
  * VChartType.AREA
  
If no type is defined, the chart type will be set to the default type which is the VChartType.DEFAULT = VChartType.COLUMN.
The chart type can be set at INIT trigger or can be fixed using the CHARTTYPE trigger.

If you want to define a new type, you need to subclass the VChartType object and define the data series by overriding the createDataSeries(VChart).
The view implementations should also be provided by implementing the UChartType component. The new chart type should be mentioned in the ChartTypeFactory class
which is responsible for creating views for every chart type.

You should note that calling setType will create the data series and refresh the chart view. So it can be called whenever you want to change the chart type. 

==== Calling charts

A chart is always called from a form, if the caller form extends from the VDictionaryForm class you have to do the following steps :

 * Change VDictionaryForm to VChartSelectionForm
 * Add the CreateChart command to the caller form
 * Implement the createChart abstract method :

*Example*
[source,java]
----
 protected VChart createChart() throws VException {
   return new UserChart(this);
 }
----

Otherwise you can create a normal form or block command that executes the following code :

[source,java]
----
   WindowController.getWindowController().doNotModal(new UserChart(this));
----

