= Kopi Application Generator :  User guide

:doctype: book

[preface]
Preface
-------
The Kopi Project is a Java software project from DMS which provides a framework for developing database applications using Java, JDBC and SWING.

Kopi contains a set of tools which allow you to edit and generate classfiles: dis (Java disassembler), KSM (Java assembler) and KJC. KJC compiles Java source code to bytecode, with all the same plus even more features as commercial compilers. KJC is available for free under the terms of the GNU Public License.

The Kopi Project also includes XKJC, a compiler for embedded SQL in Java. Built over JDBC, it allows the execution of Java-typed SQL statements and the mixing of expressions from both SQL and Java.

The last tool provided by DMS is Visual Kopi. Visual Kopi is an application framework using JDBC and JFC/Swing which lets you create database applications in a high level specification language. It also provides the ability to write triggers and commands in Java with seamlessly embedded SQL statements. 

Organization of This Document
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This documentation includes two main Chapters: +

* CHAPTER 1 : XKJC - The EXtended Kopi Java language+
XKJC is a compiler for embedded SQL in Java. This language is a super set of Java; i.e., it is compatible with Java source code. This allows the execution of Java-typed SQL statements and the mixing of expressions from both SQL and Java.

* CHAPTER 2 : VLIB - The Visual Kopi application Framework+
Visual Kopi is an application framework using SWING which lets you create database applications in a high level specification language. In this chapter, we will explore the capabilities of this framework.


== XKJC - The Extended Kopi Java language

This language extends the java language's capabilities and offer a set of additional tools.
The most important additions of the xkjc are the new types introduced and the SQL integration to java code.
To sum up, the extended kopi Java language is layer over the standard java language, meaning that all java statements are understood by the Kopi language, plus some new features and tools.
The kopi files extension is (.k).

=== XKJC : The new Types

Kopi introduces 6 types to the basic types available in the java language : 

 * Date      : date values that can be null, you can also use "date" for not null Date type values.
 * Month     : Years months values and can be null, you can use "month" for not null Month type values.
 * Week      : Years weeks values and can be null, you can use "week" for not null Month type values.
 * Time      : this type can be used to contain time values (hh:mm:ss), "time" for not null values.
 * Timestamp : can contain timestamp values and null, "timestamp" for not null values.
 
=== XKJC : Java with embedded SQL

This language allows developer to define triggers and actions in the XKJC language that is a superset of Java with embedded SQL. XKJC allows the mixing of Java-typed expression from both SQL and Java.

Since SQL statements are parsed, it allows one to write a very clear code as compared to JDBC (see XKJC vs JDBC section). It allows one to make requests with embedded Java expressions computed at runtime. It comes with a support for BLOB and Java serialization mechanism, allowing to store Java objects in any JDBC database and to retrieve them both nicely and efficiently.

As in SQL all types have a NULL value, the distinction between primitive types and Object types of the Java language are problematic. To handle this, XKJC contains an operator overloading capability that allows the mixing of primitive types with objects.

The mechanism of overloading looks like the one provided by C+.+  compiler except that only expression operator are overridable (+, -, *, /, %, ==, !=, &, |, << >>, >>>, ^, ~, ++, –) and the cast operation. There is no implicit conversion, and that make it easy to understand.

There is an example of a typical XKJC program:
 	
[source,java]
----
#cursor(int id) { 
  SELECT Vector Obj 
  FROM   BLOBS 
  WHERE  ID = :id 
} typed; 
typed.open(6); 
if (typed.next()) 
  for (int i = 0; i < typed.Obj.size(); i++) 
    System.out.println("vect(" + i + "): " + typed.Obj.elementAt(i)); 
typed.close(); 
----
 


By providing an easy way to include SQL statement inside your Java code (not between double quote), XKJC made it more easy to read and maintain. With explicit typing the compiler check that expression are correct and involve the overloading mechanism to execute expression such as:
 
==== Connections

By providing explicit connection to SQL statement you are able to work on more than one database at the same time. But since common applications work with only one database, we provide a mechanism of implicit transaction that allows to save time by wrinting:
 	
[source,java]
----
#execute{SELECT COUNT(*) FROM Cars INTO count};
----

instead of:
 	
[source,java]
----
#execute[Main.getDatabase().getFreeConnection()] {
  SELECT COUNT(*) FROM Cars INTO count
};
----
 
==== Cursors

The cursor are the common way to get more than one row of data from the database. It’s like ResultSet but it’s typed:
 
==== SQL SELECT INTO Statement

The only SQL statement in XKJC is the #execute that allow to fetch data from the database with a “SELECT INTO”.

Examples:

[source,java]
---- 	

   1. #execute {
      SELECT String name, Image image, BigDecimal speed 
      FROM   Cars
      WHERE  ID = 1 
      INTO   theName, theImage, theSpeed
    };
    	    

   2.  #execute {
      SELECT String name 
      FROM   Cars 
      WHERE  ID =:id 
      INTO   names[id]
    };
       

   3. #execute[conn] {
      SELECT COUNT(*) 
      FROM Cars 
      INTO count
    };
----
The last example use an explicit connection while the others use an implicit connection (ie, the context should inherit from DBContextHandler and its default connection will be used).
 
==== SQL Expressions

SQL expression returns an int value that correspond to the number of row modified by the expression. An expression can use a cursor to identifie a row of the database (WHERE CURRENT OF) with fully implemented JDBC drivers.

Examples:
 	
[source,java]
----
    1. #update {
      UPDATE Cars 
      WHERE  ID =:id 
      SET    name = :(javaName + '-' + id)
    };    

    2. #update(cursor) {
      UPDATE Cars 
      SET    name = :(javaName + '-' + id)
    };
    	    

    3. #update [conn] { 
      DELETE FROM Cars 
      WHERE :id > 10
    };
----
The last example use an explicit connection while the others use an implicit connection (ie, the context should inherit from DBContextHandler and its default connection will be used).
 
==== Transactions

Every SQL statements should be executed within transaction. This allows to re-execute statements interrupted by deadlock (after asking the user if he wants to) or abort a whole transaction if something is wrong (like if a Java exception is thrown). The syntax is:
 	
[source,java]
----
#protected([``an optional message'']){
  ... 
  ... // a list of Java and SQL statements
  ...
};
----

== VLIB - The Visual Kopi application framework 

The visual Kopi Framework is an application framework based using the XKJC language in order to create database applications easily.
In this chapter we will se how to create kopi powered forms,reports and print pages.
 
include::general.adoc[]
include::form.adoc[]
include::report.adoc[]
include::print.adoc[]
include::conclusion.adoc[]
