##
## Copyright (c) 1990-2006 kopiRight Managed Solutions GmbH
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 2
## as published by the Free Software Foundation.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.2 2001/05/24 19:28:03 graf Exp $
##

TOPDIR =	../../../..

PACKAGE =	com/kopiright/compiler/tools/antlr/runtime

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	ANTLRException ANTLRHashString ANTLRStringBuffer	\
		BitSet ByteBuffer CharBuffer				\
		CharFormatter CharQueue					\
		CharScanner CharStreamException				\
		CharStreamIOException CommonToken			\
		DefaultFileLineFormatter FileLineFormatter		\
		InputBuffer LLkParser LexerSharedInputState		\
		MismatchedCharException MismatchedTokenException	\
		NoViableAltException NoViableAltForCharException	\
		Parser ParserException ParserSharedInputState		\
		RecognitionException SemanticException			\
		Token TokenBuffer TokenQueue TokenStream		\
		TokenStreamException TokenStreamIOException		\
		TokenStreamRecognitionException				\
		VectorEnumerator Vector

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
