##
## Copyright (c) 1990-2016 kopiRight Managed Solutions GmbH
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2.1 as published by the Free Software Foundation.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id$
##

TOPDIR =	../../../../../../..

PACKAGE = 	org/kopi/vkopi/lib/ui/vaadin/addons/client/grid

COPYSOURCES =	true

## ----------------------------------------------------------------------
## TOOLS

JAVAFILES += 	EditorDateFieldConnector EditorEnumFieldConnector	\
		EditorEnumFieldState EditorField			\
		EditorFieldClickServerRpc EditorFieldClientRpc		\
		EditorFieldConnector EditorFieldNavigationServerRpc	\
		EditorFieldState EditorFixnumFieldConnector		\
		EditorFixnumFieldState EditorHandlingExtensionConnector	\
		EditorHandlingExtensionServerRpc			\
		EditorIntegerFieldConnector				\
		EditorIntegerFieldState EditorLabelClickServerRpc	\
		EditorLabelConnector EditorLabelState			\
		EditorMonthFieldConnector EditorTextAreaFieldConnector	\
		EditorTextAreaFieldState EditorTextChangeServerRpc	\
		EditorTextFieldConnector EditorTextFieldState		\
		EditorTimeFieldConnector EditorTimestampFieldConnector	\
		EditorWeekFieldConnector InvalidEditorFieldException	\
		VEditorDateField VEditorEnumField VEditorFixnumField	\
		VEditorIntegerField VEditorLabel VEditorMonthField	\
		VEditorTextAreaField VEditorTextField VEditorTimeField	\
		VEditorTimestampField VEditorWeekField			\
		EditorActorFieldConnector EditorActorFieldState		\
		VEditorActorField EditorImageFieldConnector		\
		EditorImageFieldState VEditorImageField	 		\
		BooleanRendererConnector BooleanRendererState		\
		EditorBooleanFieldConnector EditorBooleanFieldState	\
		EditorBooleanFieldValueChangeServerRpc			\
		VBooleanRenderer VEditorBooleanField			\
		VFocusableEditorField EditorSuggestionsQueryClientRpc	\
		EditorSuggestionsQueryServerRpc				\
		EditorBooleanFieldClientRpc				\
		BooleanRendererValueChangeServerRpc

## ----------------------------------------------------------------------
## FILES

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
