##
## Copyright (C) 1990-2005 DMS Decision Management Systems Ges.m.b.H.
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2 as published by the Free Software Foundation.
##
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.5 2003/08/07 15:34:51 lackner Exp $
##

TOPDIR =	../../../..

PACKAGE =	at/dms/vkopi/lib/ui/base

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES += JFieldLabel FieldStates JMenuButton		\
		KopiTitledBorder JButtonPanel ListDialogCellRenderer	\
		JFieldButton JBookmarkPanel JDisablePanel		\
		TextSelecter Stateful

OPTIONS =

PROPERTIES =

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
