##
## Copyright (c) 1990-2016 kopiRight Managed Solutions GmbH
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2.1 as published by the Free Software Foundation.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id$
##

TOPDIR =	../../..

PACKAGE =	org/kopi/vkopi/lib/form

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	AbstractFieldHandler BlockAlignment Commands		\
		FieldHandler  KopiAlignment				\
		LatexPrintWriter MultiFieldAlignment			\
		Triggers VBlock VBooleanCodeField			\
		VBooleanField VCodeField				\
		VColorField VConstants					\
		VDateField VDictionaryForm				\
		VDocGenerator VDictionary				\
		VField VFieldCommand VFieldException			\
		VFieldUI VFixnumCodeField				\
		VFixnumField VForm					\
		VHelpGenerator VImageField				\
		VImportedBlock VIntegerCodeField			\
		VIntegerField VListDialog 				\
		VMonthField VPosition BlockRecordListener		\
		VQueryNoRowException VQueryOverflowException		\
		VSkipRecordException					\
		VStringCodeField VStringField VTextField		\
		VTimeField VTimestampField				\
		VWeekField KopiLayoutManager				\
		FieldListener FieldChangeListener			\
		BlockListener ViewBlockAlignment FormListener		\
		PredefinedValueHandler AbstractPredefinedValueHandler	\
		Accessor ModelTransformer UBlock UChartLabel UField 	\
		UForm ULabel UMultiBlock UTextField UListDialog		\
		VBlockDefaultOuterJoin VBlockOracleOuterJoin		\
		UActorField

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
