/*
 * Copyright (c) 1990-2006 kopiRight Managed Solutions GmbH
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * $Id: DisMessages.msg,v 1.3 2001/06/04 13:30:24 graf Exp $
 */

package com.kopiright.bytecode.dis

prefix Dis
parent com.kopiright.compiler.base.CompilerMessages

message		PROCESSING
		"Processing \"{0}\"."

error		CLASS_NOT_FOUND
		"Class \"{0}\" not found"
		"DIS"
