/*
 * Copyright (c) 1990-2006 kopiRight Managed Solutions GmbH
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * $Id$
 */

package com.kopiright.vkopi.comp.print

prefix Print

error		UNDEFINDED_AUTOSIZE
		"This size is not known:\"{0}\""
		"PRINT"

error		UNDEFINED_STYLE
		"This style is not defined:\"{0}\""
		"PRINT"

error		BAD_FORMAT
		"This page format is not defined:\"{0}\""
		"PRINT"

error		UNDEFINED_BLOCK
		"This block is not defined:\"{0}\""
		"PRINT"

error           WRONG_PAGE_TRIGGER_NAME
		"This trigger is not supported \"{0}\""
		"PRINT"

