// Generated by msggen from MsggenMessages.xml
package com.kopiright.compiler.tools.msggen;

import com.kopiright.util.base.MessageDescription;

public interface MsggenMessages extends com.kopiright.compiler.base.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Message \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
}
