##
## Copyright (C) 1990-2005 DMS Decision Management Systems Ges.m.b.H.
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2 as published by the Free Software Foundation.
##
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.13 2004/04/09 09:45:17 lackner Exp $
##

TOPDIR =	../../..

PACKAGE =	at/dms/vkopi/lib/util

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	AWTToPS AbstractPrinter CachePrinter Charset437		\
		DBUtils EltronEPL2 EpsonLQ FPrinter Fax			\
		FaxException FaxPrinter FaxStatus			\
		Filter GroupHandler HylaFAXPrinter IPPPrinter		\
		KnownBugs LPrinter LabelPrinter Laserjet		\
		LpRPrinter MailPrinter Message				\
		MultiLineToolTip MultiLineToolTipUI PPaperType		\
		PixelConsumer PlatformFileWriter			\
		PreviewPrinter PrintException				\
		PrintInformation PrintJob Printer			\
		RPrinter Rexec To437 ToLatin1				\
		Utils HylaFAXUtils

#		Label EPSLabel


PROPERTIES =	vlib_messages_en vlib_messages_fr vlib_messages_de

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
