##
## Copyright (c) 1990-2009 kopiRight Managed Solutions GmbH
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 2
## as published by the Free Software Foundation.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.18 2004/06/09 17:30:25 lackner Exp $
##

TOPDIR =	../../..

PACKAGE =	com/kopiright/vkopi/lib/list

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	VBooleanCodeColumn VBooleanColumn			\
		VCodeColumn VColorColumn VColumn			\
		VConstants VDateColumn					\
		VFixnumCodeColumn VFixnumColumn				\
		VImageColumn VIntegerCodeColumn				\
		VIntegerColumn VList VListColumn			\
		VMonthColumn  VStringCodeColumn VStringColumn		\
		VTextColumn VTimeColumn					\
		VWeekColumn VTimestampColumn

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
