##
## Copyright (c) 1990-2009 kopiRight Managed Solutions GmbH
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2.1 as published by the Free Software Foundation.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id: Makefile,v 1.11 2003/10/13 14:02:05 lackner Exp $
##

TOPDIR =	../../..

PACKAGE =	com/kopiright/vkopi/lib/visual

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	ActionHandler Application 				\
		Constants DActor DFootPanel DInfoPanel			\
		DMenuBar DMenuItem DMenuTree DObject DPreferences	\
		DStatePanel DWaitPanel DWindow ProgressWindow		\
		FileChooser DHelpViewer VHelpViewer			\
		KopiAction KopiExecutable				\
		MenuItemRenderer MessageCode Module 			\
		Registry WaitDialogListener ProgressDialogListener	\
		VActor VDefaultActor VActionListener			\
		SplashScreen Utils VCommand VException			\
		VExecFailedException VHelpGenerator			\
		VInterruptException VMenuTree VRuntimeException		\
		VTrigger VWindow DPositionPanel DPositionPanelListener  \
		VDatabaseUtils WindowController SwingThreadHandler	\
		UIBuilder WaitInfoListener MessageListener		\
		VerifyConfiguration ApplicationConfiguration		\
		PrinterManager PropertyException ModelCloseListener	\
		UserConfiguration Message VlibProperties WaitWindow


OPTIONS =	ApplicationOptions

PROPERTIES =

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
