##
## Copyright (c) 1990-2016 kopiRight Managed Solutions GmbH
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2.1 as published by the Free Software Foundation.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id$
##

TOPDIR =	../../../../..

PACKAGE =	org/kopi/vkopi/lib/ui/vaadin/form

## ----------------------------------------------------------------------
## TOOLS

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	DateChooser DBlock DBlockDropHandler DChartBlock	\
		DChartHeaderLabel DField DFieldHandler DFieldUI		\
		DForm DImageField DLabel DListDialog DMultiBlock	\
		DObjectField DTextEditor DTextField KeyNavigator 	\
		VPredefinedValueHandler DGridBlock DGridMultiBlock	\
		DGridBlockCellStyleGenerator DGridBlockContainer 	\
		DGridBlockFieldHandler DGridBlockFieldUI 		\
		DGridEditorField DGridEditorLabel DGridTextEditorField	\
		DActorField DGridEditorActorField DGridEditorImageField	\
		DBooleanField DGridEditorBooleanField 			\
		DGridBlockItemSorter DRichTextEditor DGridBlockFilter

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
