##
## Copyright (c) 1990-2009 kopiRight Managed Solutions GmbH
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License version 2.1 as published by the Free Software Foundation.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##
## $Id$
##

TOPDIR =	../../..

PACKAGE =	com/kopiright/vkopi/lib/chart

## ----------------------------------------------------------------------
## FILES

JAVAFILES +=	ChartTypeFactory UChart UChartType			\
		VBooleanCodeDimension VBooleanDimension VChart		\
		VChartCommand VChartType VCodeDimension VCodeMeasure	\
		VColumn VColumnFormat VConstants VDataSeries		\
                VDateDimension VDefaultChartActor VDimension		\
		VFixnumCodeDimension VFixnumCodeMeasure			\
		VFixnumDimension VFixnumMeasure VHelpGenerator		\
		VIntegerCodeDimension VIntegerCodeMeasure		\
		VIntegerDimension VIntegerMeasure VMeasure		\
		VMonthDimension VNoRowException VPrintOptions VRow	\
		VStringCodeDimension VStringDimension VTimeDimension	\
		VTimestampDimension VWeekDimension VCodeMeasure		\
		VDimensionData

## ----------------------------------------------------------------------
## GOALS

default:	build

## ----------------------------------------------------------------------
## GLOBAL DEFINITIONS

include $(TOPDIR)/Make.Defs
