/*
 * Copyright (c) 1990-2009 kopiRight Managed Solutions GmbH
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * $Id$
 */

package com.kopiright.vkopi.lib.chart;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;

import com.kopiright.vkopi.lib.base.Utils;
import com.kopiright.vkopi.lib.visual.VCommand;

/**
 * This class implements a Kopi pretty printer
 */
public class VHelpGenerator extends com.kopiright.vkopi.lib.visual.VHelpGenerator {

  // ----------------------------------------------------------------------
  // ACCESSORS
  // ----------------------------------------------------------------------

  /**
   * prints a compilation unit
   */
  public String helpOnChart(String name,
                            VCommand[] commands,
                            VColumn[] columns,
                            String help)
  {
    try {
      File              file;
      String[]          version;
      
      file = Utils.getTempFile(name, "htm");
      p = new PrintWriter(new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), "UTF-8")));
      p.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//DE\">");
      p.println("<!--Generated by kopi help generator-->");
      p.println("<TITLE>" + name + "</TITLE>");
      p.println("<META NAME=\"description\" CONTENT=\"" + name + "\">");
      p.println("<META NAME=\"keywords\" CONTENT=\"" + name + "\">");
      p.println("<META NAME=\"resource-type\" CONTENT=\"document\">");
      p.println("<META NAME=\"distribution\" CONTENT=\"global\">");
      p.println("<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=utf-8\">");
      p.println("</HEAD>");
      p.println("<BODY BGCOLOR=#FFFFFF>");
      p.println("<CENTER><H1>" + name + "</H1></CENTER>");
      if (help != null) {
	p.println("<P>" + help + "</P>");
      }

      if (commands != null) {
        helpOnCommands(commands);
      }

      p.println("<TABLE border=\"0\" cellspacing=\"3\" cellpadding=\"2\">");
      p.println("<TR>");
      p.println("<TD><pre>    </pre>");
      p.println("</TD>");
      p.println("<TD>");
      p.println("<DL>");
      for (int i = 0; i < columns.length; i++) {
        VColumn  	column = columns[i];

        column.helpOnColumn(this);
      }
      p.println("</DL>");
      p.println("</TD>");
      p.println("</TR>");
      p.println("</TABLE>");

      p.println("<BR>");
      p.println("<ADDRESS>");
      p.println("<I>kopiRight Managed Solutions GmbH</I><BR>");
      version = Utils.getVersion();
      for (int i=0; i<version.length; i++) {
	p.println("<I>" + version[i] + "</I><BR>");
      }
      p.println("</ADDRESS>");
      p.println("</BODY>");
      p.println("</HTML>");
      p.close();
      
      return file.getPath();
    } catch (IOException e) {
      System.err.println("IO ERROR " + e);
      return null;
    }
  }

  /**
   * printlns a compilation unit
   */
  public void helpOnColumn(String label,  String help) {
    if (label == null) {
      return;
    }
    p.println("<DT>");
    p.println("<H2>" + label + "</H2>");
    p.println("<DD>");
    if (help != null) {
      p.println("<P>" + help + "</P>");
    }
  }
}
