// Generated by msggen from OptgenMessages.xml
package org.kopi.compiler.tools.optgen;

import org.kopi.util.base.MessageDescription;

public interface OptgenMessages extends org.kopi.compiler.base.CompilerMessages {
  MessageDescription	DUPLICATE_DEFINITION = new MessageDescription("Option \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
  MessageDescription	DUPLICATE_SHORTCUT = new MessageDescription("Shortcut \"{0}\" redefined in \"{1}\": previous definition in \"{2}\"", null, 0);
}
