// Generated by msggen from AntlrMessages.msg
package at.dms.compiler.tools.antlr.compiler;

import at.dms.util.base.MessageDescription;

public interface AntlrMessages extends at.dms.compiler.base.CompilerMessages {
}
