// Generated by msggen from AntlrMessages.xml
package org.kopi.compiler.tools.antlr.compiler;

import org.kopi.util.base.MessageDescription;

public interface AntlrMessages extends org.kopi.compiler.base.CompilerMessages {
}
